### ISSUE TITLE
README needs some love to show some basic information as a one or two lines in form of badges

### ISSUE THREAD

**Issue by fischa** [aerleon/aerleon#109]
## Problem
On first look at the github page the README is shown and is the landing page of the project. Many projects use badges to show the health/status of the project - this can give a good (first) impression where a project is at. The current README is lacking that.

## Proposal
Add badges for the following (not exhaustive list):
* which Python versions are supported
* what format the code is in
* pypi stats
* others?

**Comment by jtwb** [comment]
@fischa Should we mark this closed or are there other badges we might want to consider?
