### ISSUE TITLE
Automation: License & copyright checks

### ISSUE THREAD

**Issue by jtwb** [aerleon/aerleon#145]
To assist with maintainer license obligations, add a Github Action that will flag any PR that meets any of the following criteria:

* Touching the LICENSE or NOTICE files.
* Touching any "pristine" files from the Capirca repo. A "pristine" file is one that has not yet been modified by this fork and would require a modification notice be added under the terms of the Apache License. The Github Action or its configuration can contain this list of "pristine" files and we can remove files from the list once they are modified.

**Comment by ankenyr** [comment]
We have successfully checked this prior to the soft launch

**Comment by jtwb** [comment]
Right, at time of launch there are no pristine files. No action needed.
