### ISSUE TITLE
Aerleon API breaks on windows due to multiprocessing issues.

### ISSUE THREAD

**Issue by csiebert007** [aerleon/aerleon#214]
The aerleon package does install with Python on Windows, however running it does not work, since it seems that currently it calls functions only available on Linux.
I know most users will run this package on Linux only, but to be a replacement for capirca, it would be helpful if this package could also use a fallback method supported on Windows OS.
[my_acl.txt](https://github.com/aerleon/aerleon/files/10530416/my_acl.txt)
[my_acl.py.txt](https://github.com/aerleon/aerleon/files/10530419/my_acl.py.txt)

**Comment by ankenyr** [comment]
looks like this is not as easy as said.
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support
>In addition, if the module is being run normally by the Python interpreter on Windows (the program has not been frozen), then freeze_support() has no effect.

@jtwb do you have any experience with `py2exe` or the other formats mentioned?

@csiebert007 sorry but this might take us a bit longer than I expected. We will want to investigate the following

1) Of the three suggested freezing methods, which to choose
2) Integrating this into our github actions for signing and releasing
3) How this would work with pip on windows

**Comment by jtwb** [comment]
I'm not familiar at all with Windows Python support. If Aerleon had support for Windows at the fork point it shouldn't be too difficult to restore support, but we need to know the root cause and be able to test it. Are you able to reproduce this issue @ankenyr?

**Comment by ankenyr** [comment]
Debugging this a bit more, just to note `aclgen` still works as intended but your script which calls the api does not. We are looking for the root cause. You should still be able to operate in the same way that Capirca provides at this time.

**Comment by ankenyr** [comment]
Ok spent some time looking at this. Our API uses multiprocessing behind the scenes. That being the case, Windows requires you to use a main function at the minimum. We changed the example to reflect this as it will work on both Linux and Windows https://github.com/aerleon/aerleon/pull/224
I have attached a working copy of the script to this comment.

I am going to mark this issue closed but please feel free to ask follow up questions here or join our slack.

[my_acl.py.txt](https://github.com/aerleon/aerleon/files/10565736/my_acl.py.txt)

**Comment by csiebert007** [comment]
Hi!

Many thanks for looking at this and letting me know how to use it properly. 
It works just fine for me ;-)

Best regards,
   Christoph
