### ISSUE TITLE
subnet comparison in aclcheck.py not working as expected

### ISSUE THREAD

**Issue by calblox** [aerleon/aerleon#226]
I noticed that aclcheck didn't seem to be working as I expected- packets weren't matching terms I would have expected them to.

After a bit of debugging, I isolated this line as what I believe to be the root cause:
https://github.com/aerleon/aerleon/blob/61c0bc93a1366872d6798d2ca6d02509b8b5fe49/aerleon/lib/aclcheck.py#L262

I think this would work if nacaddr had the in operator overloaded to support comparisons like this, and I suspect that may be the original intent (similar to ipaddr?).

I was able to workaround the issue by changing this evaluation to:
```if addr.subnet_of(next):```, and verified that this worked as expected.

I think subnet_of also handles version comparison, so line 261 can probably be pruned as superfluous if this fix is adopted:
https://github.com/aerleon/aerleon/blob/61c0bc93a1366872d6798d2ca6d02509b8b5fe49/aerleon/lib/aclcheck.py#L261

Steps to repro issue using an included pol file- I believe both of these results are incorrect:
```
(aerleon-py3.11) cwarlick@HQ-C02ZL1ZGLVDR aerleon % python ./aerleon/aclcheck_cmdline.py -s '10.0.0.10' -d '10.0.0.11' --proto=udp --sport=53 -p policies/pol/sample_juniper_loopback.pol
  filter: LOOPBACK
          term: discard-default
                deny
(aerleon-py3.11) cwarlick@HQ-C02ZL1ZGLVDR aerleon % python ./aerleon/aclcheck_cmdline.py -s '123.123.123.123' -d '10.0.0.11' --proto=udp --sport=53 -p policies/pol/sample_juniper_loopback.pol
  filter: LOOPBACK
          term: discard-default
                deny

(aerleon-py3.11) cwarlick@HQ-C02ZL1ZGLVDR aerleon % python3
Python 3.11.1 (main, Dec 23 2022, 09:40:52) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aerleon.lib import nacaddr
>>> dot0_slash31 = nacaddr.IP("10.255.255.0/31")
>>> dot1_slash32 = nacaddr.IP("10.255.255.1/32")
>>> dot2_slash32 = nacaddr.IP("10.255.255.2/32")
>>> dot1_slash32.subnet_of(dot0_slash31)
True
>>> dot1_slash32.subnet_of(dot1_slash32)
True
>>> dot1_slash32.subnet_of(dot2_slash32)
False
>>> quit()
```

repro again with proposed fix
```
(aerleon-py3.11) cwarlick@HQ-C02ZL1ZGLVDR aerleon % python ./aerleon/aclcheck_cmdline.py -s '10.0.0.10' -d '10.0.0.11' --proto=udp --sport=53 -p policies/pol/sample_juniper_loopback.pol      
  filter: LOOPBACK
          term: accept-dns-replies (possible match)
                accept if ['est']
          term: af-mismatch
                reject
(aerleon-py3.11) cwarlick@HQ-C02ZL1ZGLVDR aerleon % python ./aerleon/aclcheck_cmdline.py -s '123.123.123.123' -d '10.0.0.11' --proto=udp --sport=53 -p policies/pol/sample_juniper_loopback.pol
  filter: LOOPBACK
          term: af-mismatch
                reject
```

I don't have permissions to submit a PR for this, apologies for putting this level of detail in an issue. I hope it helps!

**Comment by fischa** [comment]
I'm seeing the same issue with `cgrep` too in `get_nets_and_highest_prefix()` and `compare_tokens()` where `nacaddr.IP()` is called and a comparison of the returned ip object is checked via an `if ip in net:` or similar.

**Comment by calblox** [comment]
https://github.com/aerleon/aerleon/pull/229 opened as a proposed fix

**Comment by ankenyr** [comment]
Only thing left is to fix cgrep, @calblox did you want to tackle that and get credit for the issue?
