### ISSUE TITLE
should aclcheck have the ability to supply a "base-directory"?

### ISSUE THREAD

**Issue by calblox** [aerleon/aerleon#227]
This base directory could specific where your policies files are located, necessary for resolving referenced includes.

This might make compatibility with aclgen simpler and more flexible, as you can supply a base directory for aclgen but not for aclcheck. 

It appears they also have different defaults- './policies' for aclgen and '' for aclcheck

**Comment by jtwb** [comment]
This was a good catch @calblox. Thanks for the fix. See also #237 .
