### ISSUE TITLE
Config file improvements

### ISSUE THREAD

**Issue by jtwb** [aerleon/aerleon#237]
At the moment, `aclgen` can read configuration settings like `base_directory`, `definitions_directory` , `exp_info` and others from a YAML config file specified with --config_file.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/212901/216678009-2cbda04c-5d13-4c4b-a117-5118b818b2f5.png">

### 1. `aclcheck` should read the same config file.

It would be convenient to enable `aclcheck` to also read from the same config file. `base_directory` and `definitions_directory` specifically are likely going to be the same across both tools, so it would be convenient for the user to just use the same config for both.

`pol2yaml` is headed in the same direction, as it also needs `base_directory`, etc.

### 2. The config file should have a standard file name and location.

Currently the config file can be named anything so long as it is YAML. IMO it would be more standard and ergonomic to have a default name and location for the config YAML file, e.g. `aerleon.yml`. A standard name and location would match familiar python tools and it would let us set a schema on the file through JSON Schema, so users can get auto-completion and error checking in their editor.

### 3. This would still work if the CLI tools were unified.

These changes would anticipate a unified CLI if we go that route in the future.

### Proposal:

1. `aclgen`, `aclcheck`, and `pol2yaml` should check for the existence of a file named `aerleon.yml` in the current directory. If present this file will be loaded as a config file.
2. The user can still set --config_file to select a different config file.
3. The user can still override these defaults using command line args (e.g. --base_directory).
4. A JSON Schema will be registered for `aerleon.yml` so users get auto-completion and error checking in-editor (VSCode, PyCharm, VIM).

**Comment by nemith** [comment]
I think this should be a no brainer.

Also a "fresh approach" using a lot of what is found in other modern tools there would probably be an `aerleon` binary with subcommands.  

`areleon generate`
`areleon check`

etc. which would also fit this concept of a single config.

**Comment by jtwb** [comment]
> Also a "fresh approach" using a lot of what is found in other modern tools there would probably be an aerleon binary with subcommands.

Yes, this is the unified CLI idea. So far it's been very well received in discussion. This change should work smoothly with a unified CLI.

**Comment by fischa** [comment]
I was thinking in the same direction as well. Basically integrating all tools into a single one and having sub-commands for dealing with all the aspects needed (incl. cgrep features).

**Comment by fischa** [comment]
What cgrep currently offers:

```text
usage: cgrep [-h] [-d DEFS] [-i IP [IP ...]] [-t TOKEN] [-c OBJ OBJ | -g IP IP | -o OBJ [OBJ ...] | -s SVC [SVC ...] | -p PORT PROTO]

c[apirca]grep

optional arguments:
  -h, --help            show this help message and exit
  -d DEFS, --def DEFS   Network Definitions directory location.
  -c OBJ OBJ, --cmp OBJ OBJ
                        Compare the two given network definition tokens
  -g IP IP, --gmp IP IP
                        Diff the network objects to which the given IP(s) belong
  -o OBJ [OBJ ...], --obj OBJ [OBJ ...]
                        Return list of IP(s) contained within the given token(s)
  -s SVC [SVC ...], --svc SVC [SVC ...]
                        Return list of port(s) contained within given token(s)
  -p PORT PROTO, --port PORT PROTO
                        Returns a list of tokens containing the given port and protocol

  -i IP [IP ...], --ip IP [IP ...]
                        Return list of definitions containing the IP(s).
                        Multiple IPs permitted.
  -t TOKEN, --token TOKEN
                        See if an IP is contained within the given token.
                        Must be used in conjunction with -i/--ip [addr].
```
I can see the following in that list:

* looking up tokens/objects by name
* reverse lookup finding tokens/objects by IP/net or port/protocol
* is IP/net in token/object
* diff/compare two tokens/objects

What is missing IMHO for an `aerleon` CLI:
* lookup where token/object is referenced (in the policies)
* diff/compare policy

Thoughts?
