### ISSUE TITLE
Minor regression on juniper generator

### ISSUE THREAD

**Issue by XioNoX** [aerleon/aerleon#323]
After upgrading from Capirca to Aerleon, the generated `juniper` policies use `icmpv6` instead of `icmp6`
```diff
[edit firewall family inet6 filter loopback6 term allow_ok_icmp6 from]
-       next-header icmp6;
+       next-header icmpv6;
```

Both work but according to Juniper's [doc](https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/concept/firewall-filter-match-conditions-for-ipv6-traffic.html):
> Note: next-header icmp6 and next-header icmpv6 match conditions perform the same function. next-header icmp6 is the preferred option. next-header icmpv6 is hidden in the Junos OS CLI.

So there is a risk that `icmpv6` becomes decommissioned at some point and breaks.

**Comment by ankenyr** [comment]
Does your policy look like
```
  - name: foo
    protocol-except: icmp6
    action: accept
```
or 
```
  - name: bar
    protocol-except: icmpv6
    action: accept
```

The code as it exists now should be outputting verbatim what ever the protocol-except is. I believe this was the same in Capirca too.

**Comment by XioNoX** [comment]
Thanks, I tested it with https://gerrit.wikimedia.org/r/c/operations/homer/public/+/945550 which is the only location in our policies where "icmpv6" is present, but unfortunately this fails with:
> aerleon.lib.aclgenerator.UnsupportedFilterError: Protocol(s) ['icmp6'] are not supported.
